setLoading(true)
        try {
            const response = await fetch(`${apiUrl}/api/short-url`, {
                method: 'POST',
                body: JSON.stringify({ url: input }),
                headers: {
setLoading(true)
        try {
            const response = await fetch(`${apiUrl}/`, {
                method: 'POST',
                body: JSON.stringify({ url: input }),
                headers: {
	
